name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run Chromatic
        id: chromatic-step
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Log Chromatic Exit Code
        run: echo "Chromatic exit code is: ${{ steps.chromatic-step.outputs.code }}"